Add tree dropdown menu
patrickmonteiro/quasar-dashboard pull request #1
Opened 2020-03-13 02:45 UTC by Atiladanvi

**Implementation**: Add tree dropdown menu.
**Motivation**: The dashbord needs provide a component to add items the menu of dashboard easyest.
**Feature**: The menu can be configured by nav.js file. The dom can detect the page reload to activate the item relative to actual page.

**P.S**: That code fragment is from quasar  app.
 **Reference**: _https://github.com/quasarframework/quasar/blob/dev/docs/src/components/AppMenu.js_

2020-03-22 22:30 UTC, patrickmonteiro requested changes

2020-03-22 22:30 UTC, patrickmonteiro commented on src/components/AppNav.js
> +import {
Can you check if you really need to import these components from Quasar? Because in the creation of the project I left the automatic import.

2020-03-23 00:57 UTC, Atiladanvi commented on src/components/AppNav.js
> +import {
That component is no part of quasar components. So you can't auto import.

2020-03-23 01:41 UTC, Atiladanvi commented on src/components/AppNav.js
> +import {
To do that i need create a html mockup. The autoload components can be only injected in template tags

2020-03-23 16:16 UTC, patrickmonteiro commented on src/components/AppNav.js
> +import {
Ok, I get it.
Let's leave it this way.

2020-03-23 16:37 UTC, patrickmonteiro approved these changes

2020-03-23 16:37 UTC, merged